### ISSUE TITLE
movi.n immediate value decoding is incorrect

### ISSUE THREAD

**Issue by pfalcon** [themadinventor/ida-xtensa#9]
See https://github.com/pfalcon/ida-xtensa/commit/2c5ff8458893f5066a34267675e11ac5b9050d3e . I can't submit patch right away, because change is in my branch with lot of changes which is quite a chore to rebase because of https://github.com/themadinventor/ida-xtensa/commit/345236bac33f193a6ae67328e49c828af8d80eb9 ;-)

**Comment by igrr** [comment]
@pfalcon slightly OT, but do you plan to open a pull request with your changes at some point? Or do you intend to maintain your branch separately? The reason i'm asking is that i've got some changes ready which add support for the upcoming ESP32. I can open a pull request either here or rebase them against your fork (fixing whitespace along the way). Just trying to understand which would make more sense.

**Comment by pfalcon** [comment]
I submitted all non-controversial changes as I was making them. Beyond that, my fork contains features specific to https://github.com/pfalcon/ScratchABit or more obtrusive changes, like pseudo-C syntax (which is also likely requires ScratchABit, and in general, I don't test it with IDA).

Summing up, I suggest to open PR here (of course unless you want to switch to ScratchABit and eat dogfood it offers ;-) ).

**Comment by igrr** [comment]
Actually I do use ScrathABit, and I have a few fixes for it which seem to be needed for the esp32 code I'm dealing with :)
Will probably submit in both places after some cleanup. Cheers!

**Comment by pfalcon** [comment]
> Actually I do use ScrathABit

Glad to hear, and looking forward to patches! (And it's of course on my todo to rebase my fork onto latest upstream master.)
